check out into path determined by upstream
There are still references to `github.com/bitly/oauth2_proxy` in the code imports. Thus we need to check the code out into this directory structure in the pipeline, otherwise it fails to build:
```./oauthproxy.go:249:27: p.provider.GetUserName undefined (type providers.Provider has no field or method GetUserName)
./options.go:275:8: undefined: providers.OIDCProvider
./options.go:279:5: p.Verifier undefined (type providers.Provider has no field or method Verifier)
```